# Generated by Django 5.0.3 on 2025-11-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikeshop', '0004_order_shipping_addr_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_addr',
        ),
        migrations.AddField(
            model_name='order',
            name='address1',
            field=models.CharField(default='', max_length=100, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.CharField(default='', max_length=100, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='eircode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
